version: "3"

services:
  cmc-general-bot:
    image: ghcr.io/cmc-discord/bot-general:latest
    container_name: cmc-general-bot

    restart: always

    depends_on:
      - cmc-general-bot-db

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    environment:
      - "ADAPTER_MONGODB_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@cmc-general-bot-db/"

      - TOKEN
      - SENTRY_DSN

  cmc-general-bot-db:
    image: mongo
    container_name: cmc-general-bot-db

    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - cmc-general-bot-db:/data/db

volumes:
  cmc-general-bot-db:
