version: "3"
services:
  watchtower:
    image: containrrr/watchtower

    restart: always

    labels:
      com.centurylinklabs.watchtower.enable: "true"

    volumes:
     - /run/docker.sock:/var/run/docker.sock
     - /root/.docker/config.json:/config.json

    environment:
      WATCHTOWER_LABEL_ENABLE: "true"

    command: --interval 300
